sudo: required
services:
    - docker

before_install:
    - docker build -t romanturovskyy/docker_react -f Dockerfile.dev .

script:
    docker run -e CI=true romanturovskyy/docker_react npm run test -- --coverage
