version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        stdin_open: true  # https://github.com/facebook/create-react-app/issues/8688
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app